# src/MugfulMuse/WooCommerceConnectorBundle/Resources/config/services.yml
services:
    mugfulmuse_woocommerce_connector.service.api_client:
        class: MugfulMuse\WooCommerceConnectorBundle\Service\WooCommerceApiClient
        arguments:
            - '%mugfulmuse_woocommerce_connector.store_url%'
            - '%mugfulmuse_woocommerce_connector.consumer_key%'
            - '%mugfulmuse_woocommerce_connector.consumer_secret%'
            - '@logger'
        public: true
    mugfulmuse_woocommerce_connector.service.sync_service:
        class: MugfulMuse\WooCommerceConnectorBundle\Service\SyncService
        arguments:
            - '@mugfulmuse_woocommerce_connector.service.api_client'
            - '@pim_catalog.repository.product'
            - '@pim_catalog.saver.product'
            - '@mugfulmuse_woocommerce_connector.repository.field_mapping'
            - '@doctrine.orm.entity_manager'
            - '@logger'
        public: true
    mugfulmuse_woocommerce_connector.repository.field_mapping:
        class: MugfulMuse\WooCommerceConnectorBundle\Repository\FieldMappingRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - MugfulMuse\WooCommerceConnectorBundle\Entity\FieldMapping
        public: true
    mugfulmuse_woocommerce_connector.repository.sync_history:
        class: MugfulMuse\WooCommerceConnectorBundle\Repository\SyncHistoryRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - MugfulMuse\WooCommerceConnectorBundle\Entity\SyncHistory
        public: true
    mugfulmuse_woocommerce_connector.controller.woo_connector:
        class: MugfulMuse\WooCommerceConnectorBundle\Controller\WooConnectorController
        arguments:
            - '@mugfulmuse_woocommerce_connector.service.api_client'
            - '@mugfulmuse_woocommerce_connector.service.sync_service'
            - '@templating'
            - '@translator'
        public: true
    mugfulmuse_woocommerce_connector.settings_manager:
        class: MugfulMuse\WooCommerceConnectorBundle\Service\SettingsManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@logger'
        public: true
    mugfulmuse_woocommerce_connector.form.extension.menu:
        class: MugfulMuse\WooCommerceConnectorBundle\Form\Extension\MenuExtension
        arguments:
            - '@security.authorization_checker'
        tags:
            - { name: form.type_extension, extended_type: Akeneo\Platform\Bundle\UIBundle\Form\Type\NavigationMenuType }
parameters:
    mugfulmuse_woocommerce_connector.store_url: ~
    mugfulmuse_woocommerce_connector.consumer_key: ~
    mugfulmuse_woocommerce_connector.consumer_secret: ~